library(Seurat)
library(monocle)
library(ggplot2)

#Monocytes
data = readRDS("celltype.rds")
subdata <- subset(data, celltype == "Monocytes")
subdata$orig.ident <- factor(subdata$orig.ident,levels = mixedsort(as.character(unique(subdata$orig.ident))))
subdata$cluster <- factor(subdata$seurat_clusters,levels = mixedsort(as.character(unique(subdata$seurat_clusters))))
subdata$times <- as.numeric(unlist(lapply(subdata$orig.ident,function(x){gsub('d','',x)})))
mtx <- as(as.matrix(subdata@assays$RNA@counts), 'sparseMatrix')
pd <- new('AnnotatedDataFrame', data = subdata@meta.data)
fData <- data.frame(gene_short_name = row.names(mtx), row.names = row.names(mtx))
fd <- new('AnnotatedDataFrame', data = fData)
monocle_cds <- newCellDataSet(mtx,phenoData = pd,featureData = fd,lowerDetectionLimit = 0.5,expressionFamily = negbinomial.size())
monocle_cds  <- DESeq2::estimateSizeFactors(monocle_cds)
monocle_cds  <- DESeq2::estimateDispersions(monocle_cds)
pca <- plot_pc_variance_explained(monocle_cds, return_all = F)
monocle_cds <- reduceDimension(monocle_cds,max_xompoinents=2,num_dim = 20,reduction_method = 'tSNE', verbose = T)
rawgenes <- row.names(subdata)
monocle_cds <- clusterCells(monocle_cds,num_clusters = 3,method='DDRTree',frequency_thresh=0.1,clustering_genes=rawgenes)
monocle_cds <- setOrderingFilter(monocle_cds,rawgenes)
monocle_cds <- reduceDimension(monocle_cds,max_components=2,method='DDRTree')
monocle_cds <- orderCells(monocle_cds)
saveRDS(monocle_cds, "Monocytes.monocle.rds")

#BM
BMdata <- subset(subdata, orig.ident %in% c("BM0", "BM1", "BM2"))
BMdata$orig.ident <- factor(BMdata$orig.ident,levels = mixedsort(as.character(unique(BMdata$orig.ident))))
BMdata$cluster <- factor(BMdata$seurat_clusters,levels = mixedsort(as.character(unique(BMdata$seurat_clusters))))
BMdata$times <- as.numeric(unlist(lapply(BMdata$orig.ident,function(x){gsub('d','',x)})))
mtx <- as(as.matrix(BMdata@assays$RNA@counts), 'sparseMatrix')
pd <- new('AnnotatedDataFrame', data = BMdata@meta.data)
fData <- data.frame(gene_short_name = row.names(mtx), row.names = row.names(mtx))
fd <- new('AnnotatedDataFrame', data = fData)
monocle_cds <- newCellDataSet(mtx,phenoData = pd,featureData = fd,lowerDetectionLimit = 0.5,expressionFamily = negbinomial.size())
monocle_cds  <- DESeq2::estimateSizeFactors(monocle_cds)
monocle_cds  <- DESeq2::estimateDispersions(monocle_cds)
pca <- plot_pc_variance_explained(monocle_cds, return_all = F)
monocle_cds <- reduceDimension(monocle_cds,max_xompoinents=2,num_dim = 20,reduction_method = 'tSNE', verbose = T)
rawgenes <- row.names(BMdata)
monocle_cds <- clusterCells(monocle_cds,num_clusters = 3,method='DDRTree',frequency_thresh=0.1,clustering_genes=rawgenes)
monocle_cds <- setOrderingFilter(monocle_cds,rawgenes)
monocle_cds <- reduceDimension(monocle_cds,max_components=2,method='DDRTree')
monocle_cds <- orderCells(monocle_cds)
saveRDS(monocle_cds, "Monocytes.BM.monocle.rds")

#BLD
BLDdata <- subset(subdata, orig.ident %in% c("BLD0", "BLD1", "BLD2", "BLD4"))
BLDdata$orig.ident <- factor(BLDdata$orig.ident,levels = mixedsort(as.character(unique(BLDdata$orig.ident))))
BLDdata$cluster <- factor(BLDdata$seurat_clusters,levels = mixedsort(as.character(unique(BLDdata$seurat_clusters))))
BLDdata$times <- as.numeric(unlist(lapply(BLDdata$orig.ident,function(x){gsub('d','',x)})))
mtx <- as(as.matrix(BLDdata@assays$RNA@counts), 'sparseMatrix')
pd <- new('AnnotatedDataFrame', data = BLDdata@meta.data)
fData <- data.frame(gene_short_name = row.names(mtx), row.names = row.names(mtx))
fd <- new('AnnotatedDataFrame', data = fData)
monocle_cds <- newCellDataSet(mtx,phenoData = pd,featureData = fd,lowerDetectionLimit = 0.5,expressionFamily = negbinomial.size())
monocle_cds  <- DESeq2::estimateSizeFactors(monocle_cds)
monocle_cds  <- DESeq2::estimateDispersions(monocle_cds)
pca <- plot_pc_variance_explained(monocle_cds, return_all = F)
monocle_cds <- reduceDimension(monocle_cds,max_xompoinents=2,num_dim = 20,reduction_method = 'tSNE', verbose = T)
rawgenes <- row.names(BLDdata)
monocle_cds <- clusterCells(monocle_cds,num_clusters = 3,method='DDRTree',frequency_thresh=0.1,clustering_genes=rawgenes)
monocle_cds <- setOrderingFilter(monocle_cds,rawgenes)
monocle_cds <- reduceDimension(monocle_cds,max_components=2,method='DDRTree')
monocle_cds <- orderCells(monocle_cds)
saveRDS(monocle_cds, "Monocytes.BLD.monocle.rds")

